version: 2.1

orbs:
  newspack: newspack/newspack@1.4.3

jobs:
  release_wporg:
    docker:
      - image: cimg/php:7.4-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Release new version on wordpress.org
          command: ./node_modules/newspack-scripts/release-wporg.sh

workflows:
  version: 2
  all:
    jobs:
      - newspack/build
      - newspack/lint-js-scss:
          requires:
            - newspack/build
      - newspack/test-js:
          requires:
            - newspack/build
      - newspack/build-distributable:
          requires:
            - newspack/build
          archive-name: 'newspack-newsletters'
          filters:
            branches:
              only:
                - trunk
      - newspack/release:
          requires:
            - newspack/build
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
                - /^epic\/.*/
      - newspack/post-release:
          requires:
            - newspack/release
          filters:
            branches:
              only:
                - release
      - release_wporg:
          requires:
            - newspack/release
          filters:
            branches:
              only:
                - release

  php:
    jobs:
      - newspack/lint-php
      - newspack/test-php
