version: 2.1

commands:
  checkout_with_workspace:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  # Linting
  lint:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Run SCSS Linter
          command: npm run lint:js
      - run:
          name: Run JS Linter
          command: npm run lint:js
      - run:
          name: Run PHP Linter
          command: |
            composer install
            npm run lint:php

  # Release job
  release:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Install PHP dependencies
          command: composer install --no-dev --no-scripts
      - run:
          name: Release new version
          command: npm run release

workflows:
  version: 2
  main:
    jobs:
      - build
      - lint:
          requires:
            - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: 
                - release
                - alpha
